[package]
name = "epo_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version =  "4.5.46" , features = ["derive"] }
csv = "1.3.1"
dashmap = "6.1.0"
env_logger = "0.11.8"
flate2 = "1.1.2"
futures = "0.3.31"
indicatif = "0.18.0"
libxml = "0.3.7"
log = "0.4.27"
rayon = "1.11.0"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
sha1 = "0.10.6"
tar = "0.4.44"
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"] }
walkdir = "2.5.0"
zip = "4.6.0"
