cmd:
  model-path: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
  mem-fraction-static: 0.8
  chunked-prefill-size: 2048
  kv-cache-dtype: fp8_e4m3
  attention-backend: fa3
  page-size: 8
  num-continuous-decode-steps: 2
  enable-memory-saver: true
  # quantization: awq
